<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>apiclient</name>
  <version>0.0.1</version>
  <description>Nodo de conexión entre ROS 2 y la API local de FirEye</description>
  <maintainer email="mpergar9@upv.edu.es">Manuel Perez</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>example_interfaces</depend>
  <exec_depend>python3-requests</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>